name: Rust CI/CD

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - dev
      - main
    tags:
      - "v*"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run tests
        run: cargo test --verbose

  build:
    name: Build Executable
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build release
        run: cargo build --release

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: nes-emulator
          path: target/release/nes-emulator

  release:
    name: Create Release
    needs: build
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download built binary
        uses: actions/download-artifact@v4
        with:
          name: nes-emulator
          path: target/release/

      - name: Determine Release Type
        id: release_type
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "tag_name=beta-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
            echo "is_prerelease=true" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "tag_name=latest" >> $GITHUB_ENV
            echo "is_prerelease=false" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
            echo "is_prerelease=false" >> $GITHUB_ENV
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.tag_name }}
          files: target/release/nes-emulator
          draft: false
          prerelease: ${{ env.is_prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
